# Generated by Django 2.2.2 on 2019-10-13 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DicomImagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagendicom', models.FileField(max_length='450', upload_to='media/')),
                ('estudio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Estudio')),
            ],
        ),
    ]
