# Generated by Django 2.2.2 on 2019-10-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicomimagenes',
            name='imagendicom',
            field=models.FileField(upload_to='media/'),
        ),
    ]
