from django import forms
from.models import Antecedentes

class formAntecedentes(forms.ModelForm):
        
        class Meta:
            model=Antecedentes

            fields = [
                'paciente_antecedente',
                'estudio',
                'fcrv_hta' ,
                'fcrv_dta' ,
                'fecha_fcrv_hta' ,
                'fecha_fcrv_dta',
                'anteced_fliar',
                'dislipemia' ,
                'estres' ,
                'tabaquismo' ,
                'ex_tabaquismo',
                'sedentarismo' ,
                'chagas' ,
                'marcapasos' ,
                'resincron' ,
                'cdi' ,
                'crm_hta' ,
                'fecha_crm_hta',
                'pm' ,
                'pm_da' ,
                'pm_dg' ,
                'pm_cx' ,
                'pr' ,
                'pr_dg' ,
                'pr_cx' ,
                'pv',
                'pv_da' ,
                'pv_dg' ,
                'pv_cx' ,
                'infarto' ,
                'fecha_infarto_reciente' ,
                'atc1' ,
                'atc1_da' ,
                'atc1_dg' ,
                'atc1_cx' ,
                'atc1_cd' ,
                'atc1_stent_bms' ,
                'atc1_stent_des' ,
                'atc2' ,
                'atc2_da' ,
                'atc2_dg' ,
                'atc2_cx' ,
                'atc2_cd' ,
                'atc2_stent_bms' ,
                'atc2_stent_des' ,
                'atc3' ,
                'atc3_da' ,
                'atc3_dg' ,
                'atc3_cx' ,
                'atc3_cd' ,
                'atc3_stent_bms' ,
                'atc3_stent_des' ,
                'otros_antecedentes' ,
            ]

            labels = {
                #grupo-FCRV
                'paciente_antecedente':'Paciente',
                'estudio':'estudio',
                'fcrv_hta' : 'HTA',
                'fcrv_dta' :'DTA',
                'fecha_fcrv_hta' :'Fecha HTA',
                'fecha_fcrv_dta':'Fecha DTA',
                'anteced_fliar':'Antecedente familiar',
                'dislipemia' :'Displemia',
                'estres':'Estres' ,
                'tabaquismo':'TABAQUISMO' ,
                'ex_tabaquismo':'Ex tabaquismo',
                'sedentarismo':'Sedentarismo',
                'chagas':'Chagas' ,
                'marcapasos':'Marcapasos' ,
                'resincron':'Resincron' ,
                'cdi':'Cdi' ,
                #grupo-crm
                'crm_hta' :' HTA',
                'fecha_crm_hta':'Fecha crm hta',
                'pm' :'Pm',
                'pm_da':'DA' ,
                'pm_dg' :'DG',
                'pm_cx':'CX' ,
                'pr':'Pr' ,
                'pr_dg':'Pr dg' ,
                'pr_cx':'Pr cx' ,
                'pv':'Pv',
                'pv_da':'Pv da' ,
                'pv_dg' :'Pv dg',
                'pv_cx':'Pv cx' ,
                'infarto':'Infarto' ,
                'fecha_infarto_reciente':'Fecha de infarto reciente' ,
                'atc1':'Atc 1' ,
                'atc1_da':'Atc 1 da' ,
                'atc1_dg' :'Atc 1 dg',
                'atc1_cx': 'Atc 1 cx' ,
                'atc1_cd':'Atc 1 cd' ,
                'atc1_stent_bms':'Atc 1 sent bms' ,
                'atc1_stent_des':'Atc 1 sent des' ,
                'atc2' :'Atc 2',
                'atc2_da':'Atc 2 da' ,
                'atc2_dg':'Atc 2 dg' ,
                'atc2_cx':'Atc 2 cx' ,
                'atc2_cd':'Atc 2 cd' ,
                'atc2_stent_bms':'Atc 2 sen bms' ,
                'atc2_stent_des':'Atc 2 sen des' ,
                'atc3':'Atc 3' ,
                'atc3_da':'Atc 3 da',
                'atc3_dg':'Atc 3 dg' ,
                'atc3_cx' :'Atc 3 cx',
                'atc3_cd' :'Atc 3 cd',
                'atc3_stent_bms':'Atc 3 sent bms' ,
                'atc3_stent_des':'Atc 3 sent des',
                'otros_antecedentes':'Otros antecedentes' ,

            }

            widgets = {
                'paciente_antecedente':forms.Select(attrs={'class':'form-control' }),
                'estudio':forms.Select(attrs={'class':'form-control' }),
                'fcrv_hta' :forms.CheckboxInput(attrs={'class':'form-control', }),
                'fcrv_dta' :forms.CheckboxInput(attrs={'class':'form-control' }),
                'fecha_fcrv_hta':forms.DateInput(attrs={'class':'form-control ml-md-5 bordes', }),
                'fecha_fcrv_dta':forms.DateInput(attrs={'class':'form-control ml-md-5 bordes'}),
                'anteced_fliar':forms.CheckboxInput(attrs={'class':'form-control'}),
                'dislipemia' :forms.CheckboxInput(attrs={'class':'form-control'}),
                'estres':forms.CheckboxInput(attrs={'class':'form-control' }), 
                'tabaquismo':forms.CheckboxInput(attrs={'class':'form-control' }), 
                'ex_tabaquismo':forms.CheckboxInput(attrs={'class':'form-control' }),
                'sedentarismo':forms.CheckboxInput(attrs={'class':'form-control'}),
                'chagas' :forms.CheckboxInput(attrs={'class':'form-control'}),
                'marcapasos' :forms.CheckboxInput(attrs={'class':'form-control'}),
                'resincron' :forms.CheckboxInput(attrs={'class':'form-control' }),
                'cdi' :forms.CheckboxInput(attrs={'class':'form-control' }),
                'crm_hta':forms.CheckboxInput(attrs={'class':'form-control' }) ,
                'fecha_crm_hta':forms.DateInput(attrs={'class':'form-control ml-md-5 bordes'}),
                'pm' :forms.CheckboxInput(attrs={'class':'form-control' }),
                'pm_da' :forms.CheckboxInput(attrs={'class':'form-control' }),
                'pm_dg' :forms.CheckboxInput(attrs={'class':'form-control' }),
                'pm_cx' :forms.CheckboxInput(attrs={'class':'form-control ml-3' }),
                'pr' :forms.CheckboxInput(attrs={'class':'form-control' }),
                'pr_dg' :forms.CheckboxInput(attrs={'class':'form-control' }),
                'pr_cx':forms.CheckboxInput(attrs={'class':'form-control ml-3' }) ,
                'pv':forms.CheckboxInput(attrs={'class':'form-control' }),
                'pv_da' :forms.CheckboxInput(attrs={'class':'form-control' }),
                'pv_dg' :forms.CheckboxInput(attrs={'class':'form-control ml-3' }),
                'pv_cx' :forms.CheckboxInput(attrs={'class':'form-control ml-3' }),
                'infarto' :forms.CheckboxInput(attrs={'class':'form-control' }),
                'fecha_infarto_reciente':forms.DateInput(attrs={'class':'form-control ml-md-3 bordes'}) ,
                'atc1':forms.CheckboxInput(attrs={'class':'form-control' }),
                'atc1_da':forms.CheckboxInput(attrs={'class':'form-control'}),
                'atc1_dg' :forms.CheckboxInput(attrs={'class':'form-control'}),
                'atc1_cx' :forms.CheckboxInput(attrs={'class':'form-control'}),
                'atc1_cd' :forms.CheckboxInput(attrs={'class':'form-control'}),
                'atc1_stent_bms' :forms.CheckboxInput(attrs={'class':'form-control ml-4'}),
                'atc1_stent_des' :forms.CheckboxInput(attrs={'class':'form-control ml-3' }),
                'atc2' :forms.CheckboxInput(attrs={'class':'form-control' ,}),
                'atc2_da' :forms.CheckboxInput(attrs={'class':'form-control' }),
                'atc2_dg' :forms.CheckboxInput(attrs={'class':'form-control' }),
                'atc2_cx' :forms.CheckboxInput(attrs={'class':'form-control' }),
                'atc2_cd' :forms.CheckboxInput(attrs={'class':'form-control' }),
                'atc2_stent_bms' :forms.CheckboxInput(attrs={'class':'form-control' }),
                'atc2_stent_des' :forms.CheckboxInput(attrs={'class':'form-control' }),
                'atc3' :forms.CheckboxInput(attrs={'class':'form-control' }),
                'atc3_da' :forms.CheckboxInput(attrs={'class':'form-control' }),
                'atc3_dg' :forms.CheckboxInput(attrs={'class':'form-control' }),
                'atc3_cx' :forms.CheckboxInput(attrs={'class':'form-control' }),
                'atc3_cd' :forms.CheckboxInput(attrs={'class':'form-control' }),
                'atc3_stent_bms' :forms.CheckboxInput(attrs={'class':'form-control' ,}),
                'atc3_stent_des' :forms.CheckboxInput(attrs={'class':'form-control' ,}),
                'otros_antecedentes' :forms.Textarea(attrs={'class':'form-control',  'rows' : '8', 'cols':'60' }),
            }