# Generated by Django 3.1.7 on 2021-04-14 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_receta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receta',
            old_name='apelido',
            new_name='apellido',
        ),
    ]
