# Generated by Django 3.1.7 on 2021-04-15 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210414_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='distancia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
