# Generated by Django 3.1.7 on 2021-04-20 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_receta_distancia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta_Receta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta_receta', models.DateField(auto_now_add=True)),
                ('Receta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.receta', verbose_name='Recetas')),
            ],
        ),
        migrations.CreateModel(
            name='Venta_Lente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feca_venta', models.DateField(auto_now_add=True)),
                ('lente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.lente', verbose_name='Lentes')),
            ],
        ),
    ]
