# Generated by Django 2.2.2 on 2019-11-07 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mpi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpi',
            name='estudio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Estudio'),
        ),
    ]
