# Generated by Django 2.2.2 on 2019-10-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudio',
            name='indicacion',
            field=models.CharField(max_length=250, verbose_name='Indicacion'),
        ),
    ]
